# Deft configuration file
# http://github.com/gknapp/deft

development: &defaults
  blog:
    author: Greg Knapp
    name: greg's weblog
    strapline: "the more I learn, the less I know"
  docroot: /Volumes/Data/greg/code/deft/httpdocs
  layout: 
    path: /Volumes/Data/greg/code/deft/templates/layout
  db:
    adapter:  mysql
    host:     localhost
    username: greg
    password: letmein
    database: deft

production:
  extends: *defaults