# Deft configuration file
# http://github.com/gknapp/deft

development: &defaults
  blog:
    author: Greg Knapp
    name: greg's weblog
    strapline: "the more I learn, the less I know"
    url: http://gregk.me
  docroot: /Volumes/Data/greg/code/deft/httpdocs
  db:
    dsn: 'mysql:host=localhost;dbname=deft'
    username: greg
    password: letmein

production:
  extends: *defaults